drop database truonghoc2;

-- Create TRUONGHOC2 database
CREATE DATABASE TRUONGHOC2;
USE TRUONGHOC2;

-- Create TRUONG table
CREATE TABLE IF NOT EXISTS TRUONG (
    MATR VARCHAR(100) PRIMARY KEY,
    TENTR VARCHAR(100) NOT NULL,
    DCHITR VARCHAR(100) NOT NULL
);

-- Create clustered index on MATR
CREATE INDEX IDX_TRUONG_MATR ON TRUONG (MATR);

-- Create non-clustered index on TENTR
CREATE INDEX IDX_TRUONG_TENTR ON TRUONG (TENTR);

-- Create HS table
CREATE TABLE IF NOT EXISTS HS (
    MAHS VARCHAR(100) PRIMARY KEY,
    HO VARCHAR(50) NOT NULL,
    TEN VARCHAR(50) NOT NULL,
    CCCD VARCHAR(20),
    NTNS VARCHAR(100) NOT NULL,
    DCHI_HS VARCHAR(100) NOT NULL
);

-- Create clustered index on MAHS
CREATE INDEX IDX_HS_MAHS ON HS (MAHS);

-- Create HOC table
CREATE TABLE IF NOT EXISTS HOC (
    MATR VARCHAR(100),
    MAHS VARCHAR(100),
    NAMHOC VARCHAR(100),
    DIEMTB VARCHAR(100),
    XEPLOAI VARCHAR(20),
    KQUA VARCHAR(20),
    PRIMARY KEY (MATR, MAHS, NAMHOC),
    FOREIGN KEY (MATR) REFERENCES TRUONG (MATR),
    FOREIGN KEY (MAHS) REFERENCES HS (MAHS)
);

-- Create clustered index on (MATR, MAHS, NAMHOC)
CREATE INDEX IDX_HOC_MATR_MAHS_NAMHOC ON HOC (MATR, MAHS, NAMHOC);

-- Create non-clustered index on XEPLOAI
CREATE INDEX IDX_HOC_XEPLOAI ON HOC (XEPLOAI);

-- Create non-clustered index on NAMHOC
CREATE INDEX IDX_HOC_NAMHOC ON HOC (NAMHOC);
