DROP DATABASE IF EXISTS  TRUONGHOC1;

-- Create TRUONGHOC2 database
CREATE DATABASE IF NOT EXISTS TRUONGHOC1;
USE TRUONGHOC1;

-- Create TRUONG table
CREATE TABLE IF NOT EXISTS TRUONG (
    MATR INT PRIMARY KEY,
    TENTR VARCHAR(100) NOT NULL,
    DCHITR VARCHAR(100) NOT NULL
);


-- Create index on MATR
CREATE INDEX IDX_TRUONG_MATR ON TRUONG (MATR);

-- Create HS table
CREATE TABLE IF NOT EXISTS HS (
    MAHS INT PRIMARY KEY,
    HO VARCHAR(50) NOT NULL,
    TEN VARCHAR(50) NOT NULL,
    CCCD VARCHAR(20),
    NTNS VARCHAR(100) NOT NULL,
    DCHI_HS VARCHAR(100) NOT NULL
);

-- Create index on MAHS
CREATE INDEX IDX_HS_MAHS ON HS (MAHS);

-- Create HOC table
CREATE TABLE IF NOT EXISTS HOC (
    MATR VARCHAR(20),
    MAHS VARCHAR(20),
    NAMHOC VARCHAR(20),
    DIEMTB VARCHAR(10),
    XEPLOAI VARCHAR(20),
    KQUA VARCHAR(20),
    CONSTRAINT PK_HOC PRIMARY KEY (MATR, MAHS, NAMHOC),
    FOREIGN KEY (MATR) REFERENCES TRUONG (MATR),
    FOREIGN KEY (MAHS) REFERENCES HS (MAHS)
);

-- Create index on (MATR, MAHS, NAMHOC)
CREATE INDEX IDX_HOC_MATR_MAHS_NAMHOC ON HOC (MATR, MAHS, NAMHOC);
